#ifndef _GEODE_DEFAULTS_H
#define _GEODE_DEFAULTS_H

#define SHARD_FILE_EXT ".shard"

#define DEFAULT_PREFIX "/"
#define DEFAULT_SHARD_PATH DEFAULT_PREFIX "shard"
#define DEFAULT_CONFIG_PATH DEFAULT_SHARD_PATH "/configuration" SHARD_FILE_EXT
#define DEFAULT_STORE_PATH DEFAULT_SHARD_PATH  "/store"
#define DEFAULT_PKGS_PATH DEFAULT_SHARD_PATH   "/pkgs"
#define DEFAULT_MODULES_PATH DEFAULT_SHARD_PATH "/modules"

#define AMETHYST_SOURCE_PKG_NAME "amethyst-source"
#define DEFAULT_SOURCE_DIR "source"
#define VERSION_FILENAME "version"

#define DEFAULT_TMPDIR "/tmp"
#define DEFAULT_TMPFILE_FORMAT DEFAULT_TMPDIR "/%d-%x-%s"

#endif /* _GEODE_DEFAULTS_H */

