#ifndef _AMETHYST_VERSION_H
#define _AMETHYST_VERSION_H

#define AMETHYST_VERSION "0.0.1"
#define AMETHYST_COMPILATION_DATE __DATE__
#define AMETHYST_COMPILATION_TIME __TIME__

#endif /* _AMETHYST_VERSION_H */

