#!/usr/bin/env python3

import sys

num_vendors = 0
num_devices = 0

if len(sys.argv) != 3:
    print(f'Usage: {sys.argv[0]} <c target> <pci.ids file>')
    exit(1)

output = open(sys.argv[1], 'w')

output.write('''
// generated by pci-id-gen.py

#include <drivers/pci/pci.h>
#include <cdefs.h>

__section(".rodata") const struct pci_vendor_id pci_id_lookup_table[] = {
''')

def end_vendor():
    global num_vendors, num_devices, output
    if num_vendors > 0:
        output.write(f'''    }},
    .num_device_ids = {num_devices}
}},
''')

def next_vendor(vendor):
    global num_vendors, num_devices, output
    end_vendor()

    num_vendors += 1
    num_devices = 0
    
    current_vendor = vendor.split('  ')
    current_vendor[1] = current_vendor[1].replace('"', '\\"')
     
    output.write(f'''{{
    .vendor_id = 0x{current_vendor[0]},
    .vendor = "{current_vendor[1]}",
    .device_ids = (struct pci_device_id[]){{
''')
    
def next_device(device):
    global num_devices, output
    device = device.split('  ')
    device[1] = device[1].replace('"', '\\"')
    output.write(f'''        {{
            .device_id = 0x{device[0]},
            .device = "{device[1]}"
        }},
''')
    num_devices += 1

with open(sys.argv[2], "r") as f:
    for line in f:
        line = line.rstrip()
        if len(line) == 0 or line[0] in ['#', 'C']:
            continue

        fields = line.split('\t')
        if len(fields) == 1:
            next_vendor(fields[0])
        elif len(fields) == 2:
            next_device(fields[1])

end_vendor()
output.write(f'''}};
const size_t pci_id_lookup_table_size = {num_vendors};
''')

output.close()

